version: '3'
services:
  web:
    build: .
    ports:
      - "15000:5000"
    volumes:
      - ./Data:/app/Data
      - ./Input:/app/Input
      - ./Output:/app/Output
      - ./Memory:/app/Memory
    restart: always # restart the container if it crashes or if the system reboots
